defmodule GA.Repo.Migrations.AddHmacKeyToAccounts do
  use Ecto.Migration

  alias Ecto.Adapters.SQL

  def up do
    alter table(:accounts) do
      add :hmac_key, :binary
    end

    flush()
    backfill_hmac_keys()

    alter table(:accounts) do
      modify :hmac_key, :binary, null: false
    end
  end

  def down do
    alter table(:accounts) do
      remove :hmac_key
    end
  end

  defp backfill_hmac_keys do
    %{rows: rows} = SQL.query!(repo(), "SELECT id FROM accounts WHERE hmac_key IS NULL", [])

    rows
    |> Enum.map(fn [account_id] -> {account_id, :crypto.strong_rand_bytes(32)} end)
    |> Enum.chunk_every(500)
    |> Enum.each(&backfill_hmac_key_batch/1)
  end

  # Batch updates reduce migration round-trips while preserving per-account
  # cryptographic randomness generated by :crypto.strong_rand_bytes/1.
  defp backfill_hmac_key_batch(batch) do
    {account_ids, hmac_keys} = Enum.unzip(batch)

    SQL.query!(
      repo(),
      """
      UPDATE accounts AS a
      SET hmac_key = v.hmac_key
      FROM (
        SELECT *
        FROM unnest($1::uuid[], $2::bytea[]) AS v(id, hmac_key)
      ) AS v
      WHERE a.id = v.id
      """,
      [account_ids, hmac_keys]
    )
  end
end
